name: Michele Suits Photography
favicon: null
layout_spectrum: 0.18758152821101248
typography_spectrum: 0.19016829505562782
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#060603'
    - '#b5a694'
    - '#bb7055'
    - '#dbcbcb'
    - '#974330'
  brandStrength: 0.5467907546553761
  lightness: 0.5578741014469415
  saturation: 0.39017455209977925
  rhythmicContrast: 0.8687458280473948
purpose: []
